# Y1 SUMMER 2022
# Basic Course in Programming Y1
# Author: Joel Lahenius
# A test main program for the CivilizationUnit class

from civilization_unit import CivilizationUnit
import random

from civilization_unit_testing_program import fight_and_print_outcome

def main():
    seed = 1934
    random.seed(seed)
    print("(Random module has been initialized with seed {:d})".format(seed))
    print("Press enter to proceed in the story.")
    input()
    archer1 = CivilizationUnit("Archer", 7, 5, is_ranged = True)
    spearman1 = CivilizationUnit("Spearman", 11)
    print("Troops have been deployed against filthy barbarians!")
    print("In the battlefield there is a Siamese Archer:")
    print(archer1)
    input()
    print("Against a barbarian spearman:")
    print(spearman1)
    input()
    print("The archer gets the first strikes and shoots the spearman with a ranged attack!")
    fight_and_print_outcome(archer1, spearman1)
    input()
    print("The spearman suffered damage:")
    print(spearman1)
    input()
    
    print("But the archer is still healthy with full hp!")
    print(archer1)
    input()
    print("The spearman gets a chance to strike back!")
    print("However, it is wounded, so now it can only attack with the effective strength of about {:.0f}".format(spearman1.get_effective_attack_strength()))
    fight_and_print_outcome(spearman1, archer1)
    input()
    print("The archer suffered major damage:")
    print(archer1)
    input()
    print("While the spearman only a little:")
    print(spearman1)
    input()
    heal_amount = 20
    print("The archer decides it must heal {:d} HP.".format(heal_amount))
    archer1.heal(heal_amount)
    print(archer1)
    input()
    print("But the spearman attacks again.")
    print("The attack is deadlier than before, as the wounded archer is only defending with an effective strength of {:.0f}".format(archer1.get_effective_defense_strength()))
    fight_and_print_outcome(spearman1, archer1)
    input()
    print("The archer's situation looks bad:")
    print(archer1)
    input()
    print("While the spearman is alright:")
    print(spearman1)
    input()
    print("However, a nearby Siamese city has just finished a swordsman!")
    swordsman1 = CivilizationUnit("Swordsman", 14)
    print(swordsman1)
    print("It arrives just in time to help the archer")
    input()
    print("Meanwhile, the barbarian spearman has fortified")
    spearman1.fortify()
    print(spearman1)
    input()
    print("So despite of it having only {:d} HP, it defends with an increased effective strengh of about {:.0f}".format(spearman1.get_hp(), spearman1.get_effective_defense_strength()))
    input()
    print("It attacks the barbarian spearman, resulting in a brutal melee fight")
    fight_and_print_outcome(swordsman1, spearman1)
    input()
    print(spearman1)
    print(swordsman1)
    input()
    print("The archer sees its chance and shoots the final blow to the barbarian spearman!")
    fight_and_print_outcome(archer1, spearman1)
    print(spearman1)
    input()
    print("The barbarian is now eliminated and the units have time to heal up")
    swordsman1.heal(100)
    archer1.heal(100)
    input()
    print("The Siamese units are now on full HP again and can return to the town as heroes")
    archer1.unfortify()
    print(archer1)
    print(swordsman1)
    input()
    print("This was the untold story of the Siamese empire in the Ancient era")
    print("(End of program)")

if __name__ == "__main__":
    main()
